### ISSUE TITLE
Can't build with msfvenom

### ISSUE THREAD

**Issue by PropsFura** [remo7777/Termux-Apktool-V2.4.0#1]
Every time i build with it, i am getting this error. Used facebook lite as example 

Rebuilding Face.apk with meterpreter injection as /data/data/com.termux/files/usr/tmp/d20190427-32626-gwirnd/output.apk
[*] Signing failed /data/data/com.termux/files/usr/tmp/d20190427-32626-gwirnd/output.apk
[*] copying binded /data/data/com.termux/files/usr/tmp/d20190427-32626-gwirnd/output.apk application
Error: No such file or directory @ rb_sysopen - /data/data/com.termux/files/usr/tmp/d20190427-32626-gwirnd/aligned.apk

**Comment by remo7777** [comment]
that problem fixed....
git clone and install again....

**Comment by remo7777** [comment]
or 
`wget https://github.com/remo7777/Termux-Apktool-V2.4.0/archive/1.0.5.zip`

`unzip 1.0.5.zip`

`cd Termux-Apktool-V2.4.0-1.0.5`

`bash setup`

hope it ll fix
